sudo: false

language: cpp

before_install:
  - true

install:
  - true

script:
  - lscpu
  - timeout 60 ./xmrig && echo 'meh'
  - timeout 60 ./xmrig && echo 'meh'

after_failure:
  - echo ">> done <<"
